[package]
name = "pyroquad"
version = "0.0.5"
edition = "2024"


[lib]
name = "_pyroquad"
crate-type = ["cdylib", "rlib"]


[[bin]]
name = "stub_gen"
doc = false

[profile.release]
overflow-checks = true
panic = "unwind"


[dependencies]

#core dependency
macroquad = { version = "=0.4.14", features = ["audio"] }

#used to build the python library
pyo3 = { version = "=0.28.3", features = ["extension-module", "multiple-pymethods"] }

# modified version of stub gen that doesnt complain when compiling with python 3.9
pyo3-stub-gen = { git = "https://github.com/Ludwig-000/pyo3-stub-gen", branch = "patch-1", optional = true }

# up to date stub generation tool
pyo3-stub-gen-real = { package = "pyo3-stub-gen", version = "=0.22.3", optional = true }


crossbeam = "=0.8.4" # used for the main Command Queue inside lib.rs

glam = { version = "=0.27.0", features = ["scalar-math"] } # used for vector maths.


rapier3d = { version = "=0.35.0-beta.0", features = ["parallel"] } # used for DBTV trees.

reqwest = { version = "=0.13.4", features = ["blocking"] } # used for runtime-downloading assets.

slotmap = "=1.0.7" # fast hasher for object management. <3 slopmap >_<

hound = "=3.5.1" #for converting audio formats
symphonia = { version = "=0.5.5", features = ["mp3"] } #for converting audio formats

gltf = "=1.4.1" # for parsing 3DAssets

rayon = "=1.11.0" # TODO: replace with custom threading solution
paste = "=1.0.15" # for better macro control, allowing the writing of generic comments.

quad-snd = { git = "https://github.com/Ludwig-000/quad-snd " } # custom fork for quad-snd for a compatability fix for linux.

[dependencies.image] # for image decoding
version = "=0.25.8"
default-features = false
features = ["png", "jpeg", "webp"]




# this whole block soely exists to detect if the mouse is inside the window.
# TODO: find a pre-built solution ASAP!
[target.'cfg(target_arch = "windows")'.dependencies]
[dependencies.windows-sys]
version = "0.59"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
]
[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"
objc = "0.2"
[target.'cfg(target_os = "linux")'.dependencies]
x11 = "2.21"
libc = "0.2"
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["Window", "Document", "Element", "MouseEvent"] }
wasm-bindgen = "0.2"




# compile using:
# maturin build --release --features abi_314 --no-default-features
[features]

# we switch between the modified version of stub gen, and the official one, to juggle new features, and the fact that maturin supports python 3.9, while current stub gen does not.
default = ["use-dummy"]
use-dummy = ["dep:pyo3-stub-gen"]
use-real = ["dep:pyo3-stub-gen-real"]


abi_314 = ["pyo3/abi3", "pyo3/abi3-py314"] # python 3.14 and up
abi_310 = ["pyo3/abi3", "pyo3/abi3-py310"] # python 3.10 and up
abi_39 = ["pyo3/abi3", "pyo3/abi3-py39"] # python 3.9 and up